# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

CCACHE=/usr/bin/ccache
MM=/usr/bin/gcc
RC=/usr/bin/rustc
GC=/usr/bin/go
CC=/usr/bin/gcc
CXX=/usr/bin/gcc
AS=/usr/bin/gcc
CU=/opt/cuda/bin/nvcc
MXX=/usr/bin/gcc

AR=/usr/bin/ar
GCAR=/usr/bin/go
RCAR=/usr/bin/rustc
RCSH=/usr/bin/rustc
SH=/usr/bin/g++
GCLD=/usr/bin/go
RCLD=/usr/bin/rustc
LD=/usr/bin/g++
CULD=/opt/cuda/bin/nvcc

app_bench_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/b/benchmark/1.7.0/41e335b0d4864392b8c21cd6ed5e875b/include -std=c++2b -DNDEBUG
app_bench_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/b/benchmark/1.7.0/41e335b0d4864392b8c21cd6ed5e875b/include -std=c++2b -DNDEBUG
app_bench_LDFLAGS=-m64 -L/home/pablo/.xmake/packages/b/benchmark/1.7.0/41e335b0d4864392b8c21cd6ed5e875b/lib -Lapp -s -lbenchmark_main -lbenchmark -llib -lfmt -lpthread
app_test_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/g/gtest/1.12.1/20a632ab8cd449b696b952cd2c20ce18/include -std=c++2b -DNDEBUG
app_test_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/g/gtest/1.12.1/20a632ab8cd449b696b952cd2c20ce18/include -std=c++2b -DNDEBUG
app_test_LDFLAGS=-m64 -L/home/pablo/.xmake/packages/g/gtest/1.12.1/20a632ab8cd449b696b952cd2c20ce18/lib -Lapp -s -lgtest -lgtest_main -lgmock -llib -lfmt -lpthread
app_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/c/cxxopts/v3.0.0/533f1970a0884648838ce983784f4181/include -std=c++2b -DNDEBUG
app_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/c/cxxopts/v3.0.0/533f1970a0884648838ce983784f4181/include -std=c++2b -DNDEBUG
app_LDFLAGS=-m64 -Lapp -s -llib -lfmt
lib_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/c/cxxopts/v3.0.0/533f1970a0884648838ce983784f4181/include -std=c++2b -DNDEBUG
lib_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -O3 -Iinclude -I/usr/local/include -I/usr/include -isystem /home/pablo/.xmake/packages/c/cxxopts/v3.0.0/533f1970a0884648838ce983784f4181/include -std=c++2b -DNDEBUG
lib_ARFLAGS=-cr

default:  app_bench app_test app lib

all:  app_bench app_test app lib

.PHONY: default all  app_bench app_test app lib

app_bench: app/app_bench
app/app_bench: app/liblib.a build/.objs/app_bench/linux/x86_64/release/bench/lib/cipher_dsa_benchmarks.cpp.o build/.objs/app_bench/linux/x86_64/release/bench/main.cpp.o
	@echo linking.release app_bench
	@mkdir -p app
	@/usr/bin/clang++ -o app/app_bench build/.objs/app_bench/linux/x86_64/release/bench/lib/cipher_dsa_benchmarks.cpp.o build/.objs/app_bench/linux/x86_64/release/bench/main.cpp.o $(app_bench_LDFLAGS) > build/.build.log 2>&1

build/.objs/app_bench/linux/x86_64/release/bench/lib/cipher_dsa_benchmarks.cpp.o: bench/lib/cipher_dsa_benchmarks.cpp
	@echo ccache compiling.release bench/lib/cipher_dsa_benchmarks.cpp
	@mkdir -p build/.objs/app_bench/linux/x86_64/release/bench/lib
	@clang -c $(app_bench_CXXFLAGS) -o build/.objs/app_bench/linux/x86_64/release/bench/lib/cipher_dsa_benchmarks.cpp.o bench/lib/cipher_dsa_benchmarks.cpp > build/.build.log 2>&1

build/.objs/app_bench/linux/x86_64/release/bench/main.cpp.o: bench/main.cpp
	@echo ccache compiling.release bench/main.cpp
	@mkdir -p build/.objs/app_bench/linux/x86_64/release/bench
	@clang -c $(app_bench_CXXFLAGS) -o build/.objs/app_bench/linux/x86_64/release/bench/main.cpp.o bench/main.cpp > build/.build.log 2>&1

app_test: app/app_test
app/app_test: app/liblib.a build/.objs/app_test/linux/x86_64/release/test/lib/lib_tests.cpp.o build/.objs/app_test/linux/x86_64/release/test/main.cpp.o
	@echo linking.release app_test
	@mkdir -p app
	@/usr/bin/clang++ -o app/app_test build/.objs/app_test/linux/x86_64/release/test/lib/lib_tests.cpp.o build/.objs/app_test/linux/x86_64/release/test/main.cpp.o $(app_test_LDFLAGS) > build/.build.log 2>&1

build/.objs/app_test/linux/x86_64/release/test/lib/lib_tests.cpp.o: test/lib/lib_tests.cpp
	@echo ccache compiling.release test/lib/lib_tests.cpp
	@mkdir -p build/.objs/app_test/linux/x86_64/release/test/lib
	@clang -c $(app_test_CXXFLAGS) -o build/.objs/app_test/linux/x86_64/release/test/lib/lib_tests.cpp.o test/lib/lib_tests.cpp > build/.build.log 2>&1

build/.objs/app_test/linux/x86_64/release/test/main.cpp.o: test/main.cpp
	@echo ccache compiling.release test/main.cpp
	@mkdir -p build/.objs/app_test/linux/x86_64/release/test
	@clang -c $(app_test_CXXFLAGS) -o build/.objs/app_test/linux/x86_64/release/test/main.cpp.o test/main.cpp > build/.build.log 2>&1

app: app/app
app/app: app/liblib.a build/.objs/app/linux/x86_64/release/src/main.cpp.o
	@echo linking.release app
	@mkdir -p app
	@/usr/bin/clang++ -o app/app build/.objs/app/linux/x86_64/release/src/main.cpp.o $(app_LDFLAGS) > build/.build.log 2>&1

build/.objs/app/linux/x86_64/release/src/main.cpp.o: src/main.cpp
	@echo ccache compiling.release src/main.cpp
	@mkdir -p build/.objs/app/linux/x86_64/release/src
	@clang -c $(app_CXXFLAGS) -o build/.objs/app/linux/x86_64/release/src/main.cpp.o src/main.cpp > build/.build.log 2>&1

lib: app/liblib.a
app/liblib.a: build/.objs/lib/linux/x86_64/release/src/lib/lib.cpp.o
	@echo linking.release liblib.a
	@mkdir -p app
	@$(AR) $(lib_ARFLAGS) app/liblib.a build/.objs/lib/linux/x86_64/release/src/lib/lib.cpp.o > build/.build.log 2>&1

build/.objs/lib/linux/x86_64/release/src/lib/lib.cpp.o: src/lib/lib.cpp
	@echo ccache compiling.release src/lib/lib.cpp
	@mkdir -p build/.objs/lib/linux/x86_64/release/src/lib
	@clang -c $(lib_CXXFLAGS) -o build/.objs/lib/linux/x86_64/release/src/lib/lib.cpp.o src/lib/lib.cpp > build/.build.log 2>&1

clean:  clean_app_bench clean_app_test clean_app clean_lib

clean_app_bench:  clean_lib
	@rm -rf app/app_bench
	@rm -rf app/app_bench.sym
	@rm -rf build/.objs/app_bench/linux/x86_64/release/bench/lib/cipher_dsa_benchmarks.cpp.o
	@rm -rf build/.objs/app_bench/linux/x86_64/release/bench/main.cpp.o

clean_app_test:  clean_lib
	@rm -rf app/app_test
	@rm -rf app/app_test.sym
	@rm -rf build/.objs/app_test/linux/x86_64/release/test/lib/lib_tests.cpp.o
	@rm -rf build/.objs/app_test/linux/x86_64/release/test/main.cpp.o

clean_app:  clean_lib
	@rm -rf app/app
	@rm -rf app/app.sym
	@rm -rf build/.objs/app/linux/x86_64/release/src/main.cpp.o

clean_lib: 
	@rm -rf app/liblib.a
	@rm -rf app/lib.sym
	@rm -rf build/.objs/lib/linux/x86_64/release/src/lib/lib.cpp.o

